import type {
  FitPreference,
  MeasurementRegion,
  RecommendationState,
  ReferenceObservation,
  RegionalAssessment,
} from "./types";

export interface GoldenCase {
  id: string;
  targetProductId: string;
  evidencePath: "body" | "reference";
  preference: FitPreference;
  measurements?: Array<[MeasurementRegion, number, "body_circumference" | "body_length"]>;
  reference?: {
    variantId: string;
    observations: Array<[MeasurementRegion, ReferenceObservation]>;
  };
  expectedState: RecommendationState;
  expectedSizeLabel: string;
  expectedFindings: Array<[MeasurementRegion, RegionalAssessment]>;
}

// These literals are intentionally independent of the catalog generator at runtime.
// A second collaborator reviews them in artifacts/evaluation/m1-contract-case-review.csv.
export const GOLDEN_CASES: GoldenCase[] = [
  { id: "Men|Denim-body", targetProductId: "mo-men-006", evidencePath: "body", preference: "regular", measurements: [["waist", 80.32, "body_circumference"], ["hip_seat", 98.84, "body_circumference"], ["inseam", 74.58, "body_length"]], expectedState: "RECOMMENDED", expectedSizeLabel: "32×30", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"], ["inseam", "FIT"]] },
  { id: "Men|Denim-reference", targetProductId: "mo-men-006", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-men-023:brand_04:01", observations: [["waist", "just_right"], ["hip_seat", "just_right"], ["inseam", "right_length"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "28×30", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"], ["inseam", "FIT"]] },
  { id: "Men|Knitwear-body", targetProductId: "mo-men-009", evidencePath: "body", preference: "regular", measurements: [["chest_bust", 96.88, "body_circumference"]], expectedState: "RECOMMENDED", expectedSizeLabel: "M", expectedFindings: [["chest_bust", "FIT"]] },
  { id: "Men|Knitwear-reference", targetProductId: "mo-men-009", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-men-070:brand_01:01", observations: [["chest_bust", "just_right"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "XS", expectedFindings: [["chest_bust", "FIT"]] },
  { id: "Men|Outerwear-body", targetProductId: "mo-men-001", evidencePath: "body", preference: "regular", measurements: [["chest_bust", 97.66, "body_circumference"], ["shoulder_cross_back", 44.58, "body_length"], ["body_length", 62.92, "body_length"]], expectedState: "RECOMMENDED", expectedSizeLabel: "40S", expectedFindings: [["chest_bust", "FIT"], ["shoulder_cross_back", "FIT"], ["body_length", "FIT"]] },
  { id: "Men|Outerwear-reference", targetProductId: "mo-men-001", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-men-008:brand_10:01", observations: [["chest_bust", "just_right"], ["shoulder_cross_back", "right_length"], ["body_length", "right_length"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "36S", expectedFindings: [["chest_bust", "FIT"], ["shoulder_cross_back", "FIT"], ["body_length", "FIT"]] },
  { id: "Men|Shirts & Tees-body", targetProductId: "mo-men-005", evidencePath: "body", preference: "regular", measurements: [["chest_bust", 96.7, "body_circumference"]], expectedState: "RECOMMENDED", expectedSizeLabel: "M", expectedFindings: [["chest_bust", "FIT"]] },
  { id: "Men|Shirts & Tees-reference", targetProductId: "mo-men-005", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-men-070:brand_01:01", observations: [["chest_bust", "just_right"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "XS", expectedFindings: [["chest_bust", "FIT"]] },
  { id: "Men|Shorts-body", targetProductId: "mo-men-030", evidencePath: "body", preference: "regular", measurements: [["waist", 81.42, "body_circumference"], ["hip_seat", 98.58, "body_circumference"]], expectedState: "RECOMMENDED", expectedSizeLabel: "32", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"]] },
  { id: "Men|Shorts-reference", targetProductId: "mo-men-030", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-men-006:brand_01:01", observations: [["waist", "just_right"], ["hip_seat", "just_right"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "28", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"]] },
  { id: "Men|Sweatshirts-body", targetProductId: "mo-men-016", evidencePath: "body", preference: "regular", measurements: [["chest_bust", 95.78, "body_circumference"]], expectedState: "RECOMMENDED", expectedSizeLabel: "M", expectedFindings: [["chest_bust", "FIT"]] },
  { id: "Men|Sweatshirts-reference", targetProductId: "mo-men-016", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-men-095:brand_05:01", observations: [["chest_bust", "just_right"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "XS", expectedFindings: [["chest_bust", "FIT"]] },
  { id: "Men|Tailoring-body", targetProductId: "mo-men-031", evidencePath: "body", preference: "regular", measurements: [["chest_bust", 96.88, "body_circumference"], ["shoulder_cross_back", 43.48, "body_length"], ["body_length", 64.46, "body_length"]], expectedState: "RECOMMENDED", expectedSizeLabel: "40S", expectedFindings: [["chest_bust", "FIT"], ["shoulder_cross_back", "FIT"], ["body_length", "FIT"]] },
  { id: "Men|Tailoring-reference", targetProductId: "mo-men-031", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-men-001:brand_08:01", observations: [["chest_bust", "just_right"], ["shoulder_cross_back", "right_length"], ["body_length", "right_length"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "36S", expectedFindings: [["chest_bust", "FIT"], ["shoulder_cross_back", "FIT"], ["body_length", "FIT"]] },
  { id: "Men|Trousers-body", targetProductId: "mo-men-002", evidencePath: "body", preference: "regular", measurements: [["waist", 81.12, "body_circumference"], ["hip_seat", 97.56, "body_circumference"]], expectedState: "RECOMMENDED", expectedSizeLabel: "32", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"]] },
  { id: "Men|Trousers-reference", targetProductId: "mo-men-002", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-men-006:brand_01:01", observations: [["waist", "just_right"], ["hip_seat", "just_right"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "28", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"]] },
  { id: "Women|Denim-body", targetProductId: "mo-women-013", evidencePath: "body", preference: "regular", measurements: [["waist", 69.98, "body_circumference"], ["hip_seat", 97.06, "body_circumference"]], expectedState: "RECOMMENDED", expectedSizeLabel: "S", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"]] },
  { id: "Women|Denim-reference", targetProductId: "mo-women-013", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-women-093:brand_04:01", observations: [["waist", "just_right"], ["hip_seat", "just_right"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "XL", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"]] },
  { id: "Women|Dresses-body", targetProductId: "mo-women-001", evidencePath: "body", preference: "regular", measurements: [["chest_bust", 87.4, "body_circumference"], ["waist", 70.82, "body_circumference"], ["hip_seat", 96.04, "body_circumference"]], expectedState: "RECOMMENDED", expectedSizeLabel: "8/10", expectedFindings: [["chest_bust", "FIT"], ["waist", "FIT"], ["hip_seat", "FIT"]] },
  { id: "Women|Dresses-reference", targetProductId: "mo-women-001", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-women-004:brand_06:01", observations: [["chest_bust", "just_right"], ["waist", "just_right"], ["hip_seat", "just_right"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "0/2", expectedFindings: [["chest_bust", "FIT"], ["waist", "FIT"], ["hip_seat", "FIT"]] },
  { id: "Women|Knitwear-body", targetProductId: "mo-women-014", evidencePath: "body", preference: "regular", measurements: [["chest_bust", 112.12, "body_circumference"]], expectedState: "RECOMMENDED", expectedSizeLabel: "18W", expectedFindings: [["chest_bust", "FIT"]] },
  { id: "Women|Knitwear-reference", targetProductId: "mo-women-014", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-women-016:brand_05:06", observations: [["chest_bust", "just_right"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "14W", expectedFindings: [["chest_bust", "FIT"]] },
  { id: "Women|Outerwear-body", targetProductId: "mo-women-002", evidencePath: "body", preference: "regular", measurements: [["chest_bust", 88.34, "body_circumference"], ["shoulder_cross_back", 38.08, "body_length"]], expectedState: "RECOMMENDED", expectedSizeLabel: "EU 36", expectedFindings: [["chest_bust", "FIT"], ["shoulder_cross_back", "FIT"]] },
  { id: "Women|Outerwear-reference", targetProductId: "mo-women-002", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-women-003:brand_09:01", observations: [["chest_bust", "just_right"], ["shoulder_cross_back", "right_length"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "EU 32", expectedFindings: [["chest_bust", "FIT"], ["shoulder_cross_back", "FIT"]] },
  { id: "Women|Shorts-body", targetProductId: "mo-women-032", evidencePath: "body", preference: "regular", measurements: [["waist", 71.22, "body_circumference"], ["hip_seat", 95.34, "body_circumference"], ["inseam", 72.84, "body_length"]], expectedState: "RECOMMENDED", expectedSizeLabel: "4P", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"], ["inseam", "FIT"]] },
  { id: "Women|Shorts-reference", targetProductId: "mo-women-032", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-women-078:brand_03:01", observations: [["waist", "just_right"], ["hip_seat", "just_right"], ["inseam", "right_length"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "0", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"], ["inseam", "FIT"]] },
  { id: "Women|Skirts-body", targetProductId: "mo-women-011", evidencePath: "body", preference: "regular", measurements: [["waist", 70.74, "body_circumference"], ["hip_seat", 95.78, "body_circumference"]], expectedState: "RECOMMENDED", expectedSizeLabel: "EU 36", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"]] },
  { id: "Women|Skirts-reference", targetProductId: "mo-women-011", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-women-015:brand_09:01", observations: [["waist", "just_right"], ["hip_seat", "just_right"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "EU 32", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"]] },
  { id: "Women|Tailoring-body", targetProductId: "mo-women-006", evidencePath: "body", preference: "regular", measurements: [["chest_bust", 112.78, "body_circumference"], ["shoulder_cross_back", 43.17, "body_length"]], expectedState: "RECOMMENDED", expectedSizeLabel: "18W", expectedFindings: [["chest_bust", "FIT"], ["shoulder_cross_back", "FIT"]] },
  { id: "Women|Tailoring-reference", targetProductId: "mo-women-006", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-women-002:brand_08:06", observations: [["chest_bust", "just_right"], ["shoulder_cross_back", "right_length"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "14W", expectedFindings: [["chest_bust", "FIT"], ["shoulder_cross_back", "FIT"]] },
  { id: "Women|Tops-body", targetProductId: "mo-women-007", evidencePath: "body", preference: "regular", measurements: [["chest_bust", 89.66, "body_circumference"]], expectedState: "RECOMMENDED", expectedSizeLabel: "EU 36", expectedFindings: [["chest_bust", "FIT"]] },
  { id: "Women|Tops-reference", targetProductId: "mo-women-007", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-women-065:brand_02:01", observations: [["chest_bust", "just_right"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "EU 32", expectedFindings: [["chest_bust", "FIT"]] },
  { id: "Women|Trousers-body", targetProductId: "mo-women-009", evidencePath: "body", preference: "regular", measurements: [["waist", 69.32, "body_circumference"], ["hip_seat", 95.52, "body_circumference"]], expectedState: "RECOMMENDED", expectedSizeLabel: "S", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"]] },
  { id: "Women|Trousers-reference", targetProductId: "mo-women-009", evidencePath: "reference", preference: "regular", reference: { variantId: "mo-women-093:brand_04:01", observations: [["waist", "just_right"], ["hip_seat", "just_right"]] }, expectedState: "RECOMMENDED", expectedSizeLabel: "XL", expectedFindings: [["waist", "FIT"], ["hip_seat", "FIT"]] },
];
